trigger:
- master

variables:
  azureSubscription: 'afd5b462-63ec-4ab9-8735-c715f147c8d6'
  webAppNameEastUS: 'TimeOffManagement-LWA-eastus'
  webAppNameBS: 'TimeOffManagement-LWA-bs'
  environmentName: 'TimeOffManagement-LWA'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: default

    steps:

    - script: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install sqlite3 -y
      displayName: 'install sqlite3'

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install sqlite3 --save
        npm install
        npm run build --if-present
      displayName: 'npm install and build'
    
    - script: |
        sudo apt-get -y install zip
      displayName: 'install zip'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      name: default
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: TimeOffManagement-LWA-EASTUS'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppNameEastUS)
              runtimeStack: 'NODE|14-lts'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'

          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: TimeOffManagement-LWA-BS'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppNameBS)
              runtimeStack: 'NODE|14-lts'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'